//eventually the words will be autogenerated by ai
const word_bank = [
    "alabama",
    "america",
    "school",
    "job",
    "racoon"
]

let word_input_obj;
let score = document.getElementById('tries-left');
let used_letters_arr=[];
let secret_word;
let current_score;

const checkInput = (id, word_arr) => {
    var input = document.getElementById(id).value;
    var correct_letter = word_input_obj[id];
    var acceptables_values = [...Array(26)].map((_, i) => String.fromCharCode(i + 97));

    if (acceptables_values.includes(input)){
        //check if the letter is wrong
        if (input != correct_letter){
            document.getElementById(id).value = '';
            document.getElementById(id).style.background='#ff6b6b'
            
            if (!used_letters_arr.includes(input)){
                let input_ele = document.createElement('h4'); input_ele.innerHTML = input;
                document.getElementById('incorrect-letters').appendChild(input_ele);
                used_letters_arr.push(input);
                current_score --;
                score.innerHTML = current_score;
            }
        }
        //if the letter is right
        else{
            //counting the number of times this letter occurs in a word
            var occurences = word_arr.filter(x => x == input).length;
            //looping through the object
            if (occurences != 0){
                for(const key in word_input_obj){
                    if (word_input_obj[key] == input){
                        document.getElementById(key).value = input;
                        document.getElementById(key).style.background='#91ff91'
                        document.getElementById(key).readOnly = true;
                    }
                }
            }

            document.getElementById(id).readOnly = true;
            document.getElementById(id).style.background='#91ff91'
            if (!used_letters_arr.includes(input)){
                used_letters_arr.push(input);
            }
        }
    }else{
        document.getElementById(id).value = '';
        alert('You can only use letters!')
    }
    
}

const createDataset = (word_arr) => {
    var inputs = document.getElementsByClassName('letter-box');
    var inputs_list=[];
    for(var i = 0; i < inputs.length; i++){
        inputs_list.push(inputs[i].id)
    }

    word_input_obj = Object.assign(...inputs_list.map((k, i) => ({ [k]: word_arr[i] })))
}

const buildScreen = (word) => {
    secret_word = word
    let container = document.createElement('div'); container.classList.add('word-container');
        for(var i = 0; i < word.length; i++){
            let letter_box = document.createElement('input'); letter_box.type='text'; 
            letter_box.classList.add('letter-box'); letter_box.setAttribute('maxlength', '1'); letter_box.id='letter'.concat(i);

            letter_box.addEventListener('input', function() {
                checkInput(letter_box.id, word.split(''))
            })

            container.appendChild(letter_box);
        }
    document.getElementById('game-screen').appendChild(container);
    document.getElementById('letter-screen').style.display='block';
    document.getElementById('score-screen').style.display='block';
    current_score = secret_word.length + 5;
    score.innerHTML = current_score;

    createDataset(word.split(''));
    console.log(word)
}

const chooseWord = () => {
    var generated_word = word_bank[Math.floor(Math.random() * word_bank.length)]
    buildScreen(generated_word)
    
}

const restartGame = () => {
    document.getElementById('game-screen').innerHTML = '';
    document.getElementById('incorrect-letters').innerHTML = '';
    document.getElementById('tries-left').innerHTML = '';
    chooseWord();
}

var play_btn = document.getElementById('start-game');
var replay_btn = document.getElementById('replay-game')


//very first time - using start button 
if (replay_btn.classList.contains('hide')){
    play_btn.addEventListener('click', chooseWord)
    play_btn.classList.add('hide');
    replay_btn.classList.remove('hide');
}
if (play_btn.classList.contains('hide')){
    replay_btn.addEventListener('click', restartGame)
}