//eventually the words will be autogenerated by ai
const word_bank = [
    "alabama",
    "america",
    "school",
    "job",
    "racoon"
]

let word;
let tries_counter = document.getElementById('tries-count');
let tries = 0;
let guessed_letters = [];

const cleanScreen = () => {

}

const scoreManager = (current_tries, gussed_letters, correct_letters) => {
    var btns = document.getElementsByClassName('alphabet-btns');
    if(current_tries > 0){
        if (gussed_letters == correct_letters){
            for(var i = 0; i < btns.length; i++){
                document.getElementById(btns[i].id).disabled = true;
            }
            document.getElementById('start-game').innerHTML = 'Replay'
            alert('Congradulations! You Won!');
            cleanScreen();
        }
    }
    if(current_tries == 0){
        for(var i = 0; i < btns.length; i++){
            document.getElementById(btns[i].id).disabled = true;
        }
        document.getElementById('start-game').innerHTML = 'Replay';
        cleanScreen();
    }
}

const inputCheck = (input_letter) => {

    if (word.split('').includes(input_letter)){
        var fields = document.getElementsByClassName('field-' + input_letter);
        guessed_letters.push(input_letter);
        for(var i = 0; i < fields.length; i++){
            fields[i].innerHTML = input_letter;
            fields[i].classList.remove('extra-height');
        }
        document.getElementById('button-' + input_letter).style.borderColor = '#88f65c';
        document.getElementById('button-' + input_letter).disabled = true;
    }else{
        document.getElementById('button-' + input_letter).style.borderColor = '#eb6c54';
        document.getElementById('button-' + input_letter).disabled = true;
        tries--;
        console.log(tries);
        tries_counter.innerHTML = tries;
    }

    let word_arr_no_duplicates = [...new Set(word.split(''))].length
    scoreManager(tries, guessed_letters.length, word_arr_no_duplicates);
}

const buildLetterScreen = () => {
    var alphabet = [...Array(26)].map((_, i) => String.fromCharCode(i + 97));
    for (var i = 0; i < alphabet.length; i++){
        let button = document.createElement('button'); button.id = 'button-'.concat(alphabet[i]); button.classList.add('alphabet-btns');
        button.innerHTML = String(alphabet[i]).toUpperCase();
        button.addEventListener('click', function(){
            inputCheck(button.innerHTML.toLocaleLowerCase());
        })
        document.getElementById('letters-bank').appendChild(button);
    }
}

buildLetterScreen();

buildWordScreen = (word) => {
    var word_arr = word.split('');
    word_arr.forEach(i => {
        let letter_field = document.createElement('div'); letter_field.classList.add('letter-field'); letter_field.classList.add('field-'.concat(i));
        letter_field.classList.add('extra-height')
        document.getElementById('letter-field').appendChild(letter_field);
    })
}

const selectWord = () => {
    var generated_word = word_bank[Math.floor(Math.random() * word_bank.length)]
    word = generated_word;
    buildWordScreen(word);
    console.log(word)

    tries = generated_word.split('').length;
    tries_counter.innerHTML = tries;
}

document.getElementById('start-game').addEventListener('click', selectWord);